spring:
  application:
    name: user

  profiles:
   active: server
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          lob:
            '[non_contextual_creation]': true
        '[format_sql]': true
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 17282blahbla
            client-secret: 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
            scope:
              - profile
              - email

jwt:
  iss: ironman.com
  secret: KimsionKimhojuKimhodonggyu
  expiration:
    access: 600000
    refresh: 1200000

